- KachnaOnline.Business.Data/Repositories/Abstractions/IReservationItemEventRepository.cs
- KachnaOnline.Business.Data/Repositories/ReservationItemEventRepository.cs
- KachnaOnline.Business/Extensions/UserServiceExtensions.cs
- KachnaOnline.Business/Facades/BoardGamesFacade.cs
- KachnaOnline.Business/Facades/ClubStateFacade.cs
- KachnaOnline.Business/Facades/RepeatingStatesFacade.cs
- KachnaOnline.Business/Mappings/StateMappings.cs
- KachnaOnline.Business/Services/Abstractions/IBoardGamesService.cs
- KachnaOnline.Business/Services/BoardGamesService.cs
- KachnaOnline.Dto/BoardGames/ManagerBoardGameDto.cs
- KachnaOnline.Dto/BoardGames/ReservationItemDto.cs
- KachnaOnline.Dto/BoardGames/ReservationItemEventDto.cs
- KachnaOnline.Dto/ClubStates/PastStateDto.cs
- KachnaOnline.Dto/ClubStates/RepeatingStateManagerDto.cs
- KachnaOnline.Dto/ClubStates/StateDto.cs
- KachnaOnline.Dto/Users/MadeByUserDto.cs
- KachnaOnline.Dto/Users/UserDetailsDto.cs
As discussed previously, this will make it easier for frontend to display the information.
> Use details about users rather than their IDs

- ClientApp/KachnaOnline/src/app/app.component.ts
- ClientApp/KachnaOnline/src/app/navigation-bar/navigation-bar.component.html
- ClientApp/KachnaOnline/src/app/shared/services/authentication.service.ts
- ClientApp/KachnaOnline/src/app/users/login/login.component.ts
- ClientApp/KachnaOnline/src/app/users/user-profile/user-profile.component.ts
- ClientApp/KachnaOnline/src/environments/ienvironment.ts
- ClientApp/KachnaOnline/src/index.html
This PR improves the basic frontend structure with additional functionality, namely:
- redirect to the previous site after login,
- store and load user data persistent through page refreshes or browser closing and reopening and
- change browser tab content, both icon and text.
> Frontend structure improvements

- ClientApp/KachnaOnline/src/app/app.component.ts
- ClientApp/KachnaOnline/src/app/shared/services/authentication.service.ts
- ClientApp/KachnaOnline/src/environments/environment.prod.ts
- ClientApp/KachnaOnline/src/environments/ienvironment.ts
This PR adds additional functionality to the frontend project structure.
> Improve frontend structure

- ClientApp/KachnaOnline/src/app/models/states/club-state.model.ts
- ClientApp/KachnaOnline/src/app/models/users/made-by-user.model.ts
This PR adds model for club state returned by Kachna Online API.
> Create model for club state

- ClientApp/KachnaOnline/src/app/models/states/club-state-types.model.ts
- ClientApp/KachnaOnline/src/app/models/states/club-state.model.ts
This PR adds enumeration for club state types as retuned by Kachna Online API.
> Add enum for club state types

- ClientApp/KachnaOnline/src/app/navigation-bar/navigation-bar.component.html
This PR hides the states button from the navigation bar when the user is not a states manager.
> Hide States button from navbar for unauthorized users

- KachnaOnline.App/Controllers/BoardGamesReservationsController.cs
- KachnaOnline.Business/Facades/BoardGamesFacade.cs
Will be useful for re-fetching item expiration when a manager on FE extends it without having to fetch the whole reservation
> Add endpoint for getting reservation item info

- KachnaOnline.Business/Facades/BoardGamesFacade.cs
- KachnaOnline.Business/Services/Abstractions/IBoardGamesService.cs
- KachnaOnline.Business/Services/BoardGamesService.cs
- KachnaOnline.Dto/BoardGames/ReservationItemDto.cs
This allows frontend to completely determine which actions can be
performed with a reservation item.
Fixes: #39
> Add last event type to ReservationItemDto

- ClientApp/KachnaOnline/src/app/models/users/user.model.ts
- ClientApp/KachnaOnline/src/app/shared/services/authentication.service.ts
- ClientApp/KachnaOnline/src/app/users/user-detail/manage-user-roles/manage-user-roles.component.html
- ClientApp/KachnaOnline/src/app/users/user-detail/manage-user-roles/manage-user-roles.component.ts
- ClientApp/KachnaOnline/src/app/users/user-detail/manage-user-roles/user-role/user-role.component.css
- ClientApp/KachnaOnline/src/app/users/user-detail/manage-user-roles/user-role/user-role.component.html
- ClientApp/KachnaOnline/src/app/users/user-detail/manage-user-roles/user-role/user-role.component.ts
- ClientApp/KachnaOnline/src/app/users/user-detail/user-detail.component.html
- ClientApp/KachnaOnline/src/app/users/user-detail/user-detail.component.ts
- ClientApp/KachnaOnline/src/app/users/user-profile/user-profile.component.ts
- ClientApp/KachnaOnline/src/app/users/users-list/users-list.component.html
- ClientApp/KachnaOnline/src/app/users/users-list/users-list.component.ts
- ClientApp/KachnaOnline/src/app/users/users-routing.module.ts
- ClientApp/KachnaOnline/src/app/users/users.module.ts
This PR implements basic user management and role assignment functionality.
> User management

- ClientApp/KachnaOnline/src/app/events/linked-states/manage-linked-states/manage-linked-states.component.html
- ClientApp/KachnaOnline/src/app/events/linked-states/manage-linked-states/manage-linked-states.component.ts
- ClientApp/KachnaOnline/src/app/shared/services/events.service.ts
This PR updates events module with additional functionality and validity checks.
> Update events module

- ClientApp/KachnaOnline/src/app/app.module.ts
- ClientApp/KachnaOnline/src/app/navigation-bar/loading-spinner/loading-spinner.component.html
- ClientApp/KachnaOnline/src/app/navigation-bar/loading-spinner/loading-spinner.component.ts
- ClientApp/KachnaOnline/src/app/navigation-bar/navigation-bar.component.html
- ClientApp/KachnaOnline/src/app/shared/interceptors/loading.interceptor.ts
- ClientApp/KachnaOnline/src/app/shared/services/loader.service.ts
I also added some delay for the spinner to kick in since I feel that it is a bit distracting when something white blinks in the corner for just a few milliseconds. Also maybe the color should be different but this should probably be done when we are going to be working on the remaining styling issues so that everything is consistent
> Add a spinner when data is being loaded

- ClientApp/KachnaOnline/src/app/home/repeating-states/repeating-states.component.html
- ClientApp/KachnaOnline/src/app/navigation-bar/navigation-bar.component.html
This PR fixes navigation bar sharp edges around buttons caused by incorrect grouping of buttons.
> Navigation bar fixes

- ClientApp/KachnaOnline/src/app/events/current-events/current-events.component.html
- ClientApp/KachnaOnline/src/app/events/edit-events/edit-events.component.html
- ClientApp/KachnaOnline/src/app/events/event-form/event-form.component.html
- ClientApp/KachnaOnline/src/app/events/event-form/event-form.component.ts
- ClientApp/KachnaOnline/src/app/events/events-from-all/events-from-all.component.html
- ClientApp/KachnaOnline/src/app/events/events-list/events-list.component.html
- ClientApp/KachnaOnline/src/app/events/events.module.ts
- ClientApp/KachnaOnline/src/app/events/linked-states/conflicting-states/conflicting-states.component.html
- ClientApp/KachnaOnline/src/app/events/linked-states/manage-linked-states/manage-linked-states.component.html
- ClientApp/KachnaOnline/src/app/events/next-events/next-events.component.html
- ClientApp/KachnaOnline/src/app/shared/services/events.service.ts
- ClientApp/KachnaOnline/src/app/states/plan-state/plan-state.component.ts
- KachnaOnline.Business/Services/EventsService.cs
This PR contains:
- date time picker for planning or modifying events,
- user-friendly messages instead of empty tables for events and linked states.
> Add date time picker for events

- ClientApp/KachnaOnline/src/app/board-games/manager/manager-board-games/board-game-create-form/board-game-create-form.component.html
- ClientApp/KachnaOnline/src/app/board-games/manager/manager-board-games/board-game-create-form/board-game-create-form.component.ts
HTML select and options are just stupid, however ng-bootstrap dropdown
seems to work nicely so use it instead.
> Fix update game form

- ClientApp/KachnaOnline/src/app/board-games/manager/manager-board-games/board-game-create/board-game-create.component.ts
- ClientApp/KachnaOnline/src/app/events/event-detail/event-detail.component.html
- ClientApp/KachnaOnline/src/app/events/event-form/event-form.component.html
- ClientApp/KachnaOnline/src/app/events/event-form/event-form.component.ts
- ClientApp/KachnaOnline/src/environments/ienvironment.ts
This PR improves event add/edit form by allowing image upload and adding some input validation.
> Improve events form

- ClientApp/KachnaOnline/src/app/board-games/board-games-page/board-game-card/reservation-button/reservation-button.component.html
- ClientApp/KachnaOnline/src/app/board-games/board-games-page/board-games-page.component.css
- ClientApp/KachnaOnline/src/app/board-games/board-games-page/board-games-page.component.html
- ClientApp/KachnaOnline/src/app/board-games/board-games-page/board-games-page.component.ts
- ClientApp/KachnaOnline/src/app/board-games/manager/manager-board-games/board-game-create-form/board-game-create-form.component.html
- ClientApp/KachnaOnline/src/app/board-games/manager/manager-board-games/board-game-create-form/board-game-create-form.component.ts
- ClientApp/KachnaOnline/src/app/board-games/manager/manager-board-games/manager-board-games.component.ts
- ClientApp/KachnaOnline/src/app/board-games/manager/manager-reservation-details/manager-reservation-details.component.html
- ClientApp/KachnaOnline/src/app/board-games/manager/manager-reservation-details/manager-reservation-details.component.ts
- ClientApp/KachnaOnline/src/app/board-games/manager/manager-reservations/manager-reservations.component.html
- ClientApp/KachnaOnline/src/app/board-games/manager/manager-reservations/manager-reservations.component.ts
- ClientApp/KachnaOnline/src/app/board-games/reservation-creation/reservation-creation.component.html
- ClientApp/KachnaOnline/src/app/board-games/reservation-creation/reservation-creation.component.ts
- ClientApp/KachnaOnline/src/app/navigation-bar/navigation-bar.component.html
- ClientApp/KachnaOnline/src/app/navigation-bar/navigation-bar.component.ts
- ClientApp/KachnaOnline/src/app/shared/components/user-search/user-search.component.ts
- ClientApp/KachnaOnline/src/app/shared/services/board-games-store.service.ts
- ClientApp/KachnaOnline/src/app/shared/services/board-games.service.ts
- a simple form fix
- adding new items to a reservation
- creating a reservation for a user
> Improvements to manager part of board-games

- KachnaOnline.App/Controllers/PushSubscriptionsController.cs
- KachnaOnline.App/Extensions/ControllerBaseExtensions.cs
- KachnaOnline.Business/Exceptions/PushNotifications/KeysNotAvailableException.cs
- KachnaOnline.Business/Facades/PushSubscriptionsFacade.cs
- KachnaOnline.Business/Services/BoardGamesNotifications/NotificationHandlers/PushBoardGamesNotificationHandler.cs
- KachnaOnline.Business/Services/Push/PushNotificationClient.cs
- KachnaOnline.Business/Services/StatePlanning/TransitionHandlers/PushNotificationTransitionHandler.cs
> Do not allow push configuration to be null

- ClientApp/KachnaOnline/src/app/events/event-detail/event-detail.component.html
- ClientApp/KachnaOnline/src/app/events/event-form/event-form.component.ts
- ClientApp/KachnaOnline/src/app/models/events/base-event.model.ts
- ClientApp/KachnaOnline/src/app/models/events/event-modification.model.ts
- ClientApp/KachnaOnline/src/app/models/events/event.model.ts
- ClientApp/KachnaOnline/src/app/shared/services/events.service.ts
This PR adds more meaningful error messages to event planning or event modifying, and fixes some errors bound to events and their planning.
> Show meaningful error messages for events creation/update

- ClientApp/KachnaOnline/src/app/home/events-overview/events-overview-text/events-overview-text.component.html
- ClientApp/KachnaOnline/src/app/home/events-overview/events-overview-text/events-overview-text.component.ts
- ClientApp/KachnaOnline/src/app/home/home.component.css
- ClientApp/KachnaOnline/src/app/navigation-bar/navigation-bar.component.html
- ClientApp/KachnaOnline/src/app/shared/components/components.module.ts
- ClientApp/KachnaOnline/src/app/shared/components/month-selection/month-selection.component.html
- ClientApp/KachnaOnline/src/app/shared/components/month-selection/month-selection.component.ts
- ClientApp/KachnaOnline/src/app/shared/components/togglable-button/toggleable-button.component.html
- ClientApp/KachnaOnline/src/app/shared/components/togglable-button/toggleable-button.component.ts
- ClientApp/KachnaOnline/src/app/shared/services/states.service.ts
- ClientApp/KachnaOnline/src/app/shared/utils/date-utils.ts
- ClientApp/KachnaOnline/src/app/states/plan-state/plan-state.component.html
- ClientApp/KachnaOnline/src/app/states/plan-state/plan-state.component.ts
- ClientApp/KachnaOnline/src/app/states/states-list/states-list.component.html
- ClientApp/KachnaOnline/src/app/states/states-list/states-list.component.ts
- ClientApp/KachnaOnline/src/app/states/states-routing.module.ts
- ClientApp/KachnaOnline/src/app/states/states.module.ts
- ClientApp/KachnaOnline/src/styles.css
This PR adds a club state history management page. It also refactors the `plan-state` component that is now used for creating and modifying both the current and planned states.
> Club state history and plan

- ClientApp/KachnaOnline/src/app/events/event-form/event-form.component.html
This quick PR improves positioning of events date time pickers.
> Arrange date time pickers below each other

- ClientApp/KachnaOnline/src/app/events/events-list/events-list.component.html
- ClientApp/KachnaOnline/src/app/navigation-bar/navigation-bar.component.html
This PR adds colour coding to events list.
> Add colour coding to events list

- ClientApp/KachnaOnline/src/app/navigation-bar/navigation-bar.component.html
This PR fixes positioning of Users button in navigation bar.
> Fix users button formatting

- ClientApp/KachnaOnline/src/app/board-games/board-games-page/board-games-page.component.html
- ClientApp/KachnaOnline/src/app/board-games/board-games-page/board-games-page.component.ts
- ClientApp/KachnaOnline/src/app/board-games/board-games-page/category-selector/category-selector.component.html
- ClientApp/KachnaOnline/src/app/board-games/manager/manager-board-games/board-game-create-form/board-game-create-form.component.html
- ClientApp/KachnaOnline/src/app/board-games/manager/manager-board-games/manager-board-games.component.html
- ClientApp/KachnaOnline/src/app/board-games/reservation-creation/reservation-creation.component.ts
- ClientApp/KachnaOnline/src/app/board-games/reservation-details/reservation-details-item/reservation-details-item-normal/reservation-details-item-normal.component.html
- ClientApp/KachnaOnline/src/app/board-games/reservation-details/reservation-details-item/reservation-details-item-normal/reservation-details-item-normal.component.ts
- ClientApp/KachnaOnline/src/app/board-games/reservation-details/reservation-details-item/reservation-details-item-xs/reservation-details-item-xs.component.html
- ClientApp/KachnaOnline/src/app/board-games/reservation-details/reservation-details-item/reservation-details-item.component.ts
- ClientApp/KachnaOnline/src/app/board-games/reservation-details/reservation-details.component.html
- ClientApp/KachnaOnline/src/app/board-games/reservation-details/reservation-items/reservation-items.component.html
- ClientApp/KachnaOnline/src/app/board-games/reservations/reservation-table/reservation/reservation.component.html
- ClientApp/KachnaOnline/src/app/home/events-overview/events-overview-calendar/events-overview-calendar.component.ts
- ClientApp/KachnaOnline/src/app/home/events-overview/events-overview-text/events-overview-text.component.html
- ClientApp/KachnaOnline/src/app/home/events-overview/events-overview-text/events-overview-text.component.ts
- ClientApp/KachnaOnline/src/app/home/events-overview/events-overview.component.ts
- ClientApp/KachnaOnline/src/app/home/events-overview/state-modal/state-modal.component.html
- ClientApp/KachnaOnline/src/app/shared/services/calendar-store.service.ts
- ClientApp/KachnaOnline/src/styles.css
- KachnaOnline.App/Controllers/ClubInfoController.cs
- KachnaOnline.App/Startup.cs
This fixes things discovered by testing, namely:
- Monday is now displayed as the first day of the week
- Current calendar month is maintained during navigation through the page
- Internal notes are shown in modals + visual indication of a note has been added to both state views
- Only the cell with board game name in reservation now redirects to the game.
- Some label renaming in reservations for improved clarity + better messages
- Fixed combinations of filtering, especially with name typeahead
> Various frontend improvements
